### ISSUE TITLE
Subscription support

### ISSUE THREAD

**Issue by derwaldgeist** [Gazuntype/GraphQL-Unity-Client#3]
Hi, thanks for sharing this code. I'm looking for a GraphQL client with subscription support. Does this client support subscriptions? If not, do you have plans to support them?

**Comment by gazuntype** [comment]
Hey @derwaldgeist . Just saw this. Really sorry about the late response. It currently does not support subscription but that is definitely on the roadmap for it.

**Comment by derwaldgeist** [comment]
Thanks for the info anyways!
