### ISSUE TITLE
Authentication Bearer

### ISSUE THREAD

**Issue by emorling** [Gazuntype/GraphQL-Unity-Client#4]
Do we need to implement Authentication Bearer, or this part of the lib?

**Comment by gazuntype** [comment]
Hey Emorling. The Authentication Bearer is part of the library. Just ensure the static variable auth in set to the value of the token.

**Comment by gazuntype** [comment]
So therefore, setting GraphQuery.auth to the token you want to use for authentication, sets the authorization header in the request to the token.

**Comment by emorling** [comment]
GraphQuery doesn't seem to have a variable named auth?

`GraphQuery.auth = 'MY_TOKEN';`

**Comment by emorling** [comment]
I see there is a authToken variable in the script in the repo. But It's not included in the .unitypackage?

**Comment by gazuntype** [comment]
Oh wow. That's a terrible mistake on my part. I added authentication fairly recently so I think I forgot to re-export the unitypackage. I'll do that today.

**Comment by gazuntype** [comment]
Done.
